### PR TITLE
pop older stash when no file found to stash at the starting part of script

### PR DESCRIPTION
**Pull request by hkulekci**
please test the pr. I could not tested yet. @erayalakese

### CODE REVIEW

**Comment by erayalakese** [comment]
This PR not possible to merge because I think you've deleted your fork. Can you recreate your fork to merge this PR? @hkulekci Or I'll add you as contributor to repo.

**Comment by hkulekci** [comment]
#3 I create a new pr. you can check and merge with squash

**Comment by hkulekci** [comment]
ping @erayalakese

**Comment by erayalakese** [comment]
Thank you for your patch, merged :) @hkulekci

**Pull request closed without merging**
